[browser]
serverAddress = '0.0.0.0'

[global]
dataFrameSerialization = "legacy"

[theme]
# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base = "light"

# Used to style primary interface elements. It's the color displayed most
# frequently across your app's widgets (slider, checkbox, buttons)
primaryColor = "rgb(50,172,49)" # custom purple

# Background color for the main container.
# backgroundColor = "rgba(254,248,239,1)"
# backgroundColor = "rgb(165, 207, 79)"
# Used as the background for most widgets (sidebar, text input etc.)
#secondaryBackgroundColor =  "rgb(165, 207, 79)"

# Font color for the page.
# textColor = "#0072c6"

# Font family for the page. (One of "serif", "sans serif" or "mono")
# font = "sans serif"